export 'home_page.dart';
export 'anime_detail_page.dart';
export 'character_detail_page.dart';
export 'favourite_page.dart';
export 'releases_page.dart';
export 'category_related_anime_page.dart';
export 'character_list_page.dart';
export 'category_list_page.dart';
export 'splash_screen.dart';
